Repository eclipse-zenoh/zenoh-backend-influxdb, pull requests merged in 2024-12, with the labels that each got.

#284 bug: Fixes writing binary data to influxdb...
  v1/src/lib.rs
Labels: bug

#294 README: update zenohd instructions to load REST plugin
  README.md
  v1/README.md
  v2/README.md
Labels: documentation

#308 Add CI for checking markdown format.
  .github/workflows/ci.yml
  .markdownlint.yaml
  README.md
  v1/README.md
  v2/README.md
Labels: internal

#303 bug: Fixed payload written to influxdb 2
  v2/src/lib.rs
Labels: bug
