Repository eclipse-zenoh/zenoh-backend-influxdb, pull requests merged in 2024-09, with the labels that each got.

#209 Add Example configs for V1 and V2
  README.md
  v1/EXAMPLE_CONFIG.json5
  v2/EXAMPLE_CONFIG.json5
Labels: documentation

#211 Fix influxdb `_time` argument parsing
  v1/src/lib.rs
  v2/src/lib.rs
Labels: bug

#217 Use volume credentials when none are provided in storage config
  v2/EXAMPLE_CONFIG.json5
  v2/src/lib.rs
Labels: enhancement

#220 Fix Influxdb-v2 range construction
  v2/src/lib.rs
Labels: bug

#222 Update zenoh
  Cargo.lock
Labels: internal

#224 Update zenoh
  Cargo.lock
Labels: internal

#234 Fix sync lock
  Cargo.lock
  v1/src/lib.rs
  v2/src/lib.rs
Labels: internal

#236 Align TimeRange with Rust
  Cargo.lock
  v1/src/lib.rs
  v2/src/lib.rs
Labels: internal

#242 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
